# Generated by Django 5.0 on 2024-02-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmodel',
            name='has_sub_group',
            field=models.BooleanField(default=False),
        ),
    ]
