# Generated by Django 5.0 on 2024-01-12 13:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('role_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'Role',
                'ordering': ['role_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='useraccountmodel',
            options={'ordering': ['username'], 'verbose_name': 'User Account'},
        ),
        migrations.RenameField(
            model_name='useraccountmodel',
            old_name='account_id',
            new_name='id',
        ),
    ]
