# Generated by Django 5.0 on 2024-02-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_groupmodel_has_sub_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groupmodel',
            table='GroupModel',
        ),
    ]
