# Generated by Django 5.0 on 2024-02-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_groupmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='has_sub_group',
            field=models.BooleanField(),
        ),
    ]
