# Generated by Django 5.0 on 2024-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_groupmodel_has_sub_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmodel',
            name='has_sub_group',
            field=models.BooleanField(null=True),
        ),
    ]
