import React from 'react'
import GroupList from '../../groups/groupviews/GroupList'

const UserCreationSummary = () => {
  return (
    <div className='px-16 flex flex-col py-5'>
      <div className='border-b pb-1'>
        <h1 className='font-Rubik text-[#000] text-opacity-70'>Identity Summary</h1>
        <p className='text-[12px] text-[#333] text-opacity-45 pt-1'>
          it's summary of the user information. after you create the user, you can view and download the autogenerated password and relevant information
        </p>
      </div>
      <div className='flex flex-col gap-2 border-b'>
        <h1 className='font-Rubik text-[#000] text-opacity-50 pt-6'>User Detaiil</h1>
        <div className='flex space-x-5 py-5 px-6'>
          <div className='flex flex-col gap-2 text-sm text-right font-bold'>
              <h1>Username</h1>
              <h1>Access Type</h1>
              <h1>System Password</h1>
              <h1>Custom Password</h1>
          </div>
          <div className='flex-grow flex flex-col gap-2 text-sm text-[#333] text-opacity-75'>
              <h1>useraccount_one_iam</h1>
              <h1>Programmatic access and IAM Management console access</h1>
              <h1>No</h1>
              <h1>password123422</h1>
          </div>
        </div>
      </div>
        <div className=''>
        <h1 className='font-Rubik text-[#000] text-opacity-50 pt-6'>Groups Assigned</h1>
          <GroupList />
        </div>
     
    </div>
  )
}

export default UserCreationSummary
