import React from 'react'
import GroupList from '../../groups/groupviews/GroupList'
import useUserContext from '../context/useUserContext'

const UserCreationSummary = () => {
  const {newUserAccount} = useUserContext()
  return (
    <div className='px-16 flex flex-col py-5'>
      <div className='border-b pb-1'>
        <h1 className='font-Rubik text-[#000] text-opacity-70'>Identity Summary</h1>
        <p className='text-[12px] text-[#333] text-opacity-45 pt-1'>
          it's summary of the user information. after you create the user, you can view and download the autogenerated password and relevant information
        </p>
      </div>
      <div className='flex flex-col gap-2'>
        <h1 className='font-Rubik text-[#000] text-opacity-50 pt-6'>User Detaiil</h1>
        <div className='summary w-2/3'>
           <table className='table'>
              <tbody>
                <tr>
                  <td>Username</td>
                  <td className={`whitespace-nowrap ${newUserAccount?.username === '' && 'text-red-700 text-opacity-80'}`}>{newUserAccount?.username || 'Not Available'}</td>
                </tr>
                <tr>
                  <td>Email</td>
                  <td className={`whitespace-nowrap ${newUserAccount?.email === '' && 'text-red-700 text-opacity-80'}`}>{newUserAccount?.email || 'Not Available'}</td>
                </tr>
                <tr>
                  <td>Access Type</td>
                  <td className={`whitespace-nowrap ${newUserAccount?.accessType === false && 'text-red-700 text-opacity-80'}`}>{newUserAccount?.accessType || 'Not Available'}</td>
                </tr>
                <tr>
                  <td>System Password</td>
                  <td className={`whitespace-nowrap ${newUserAccount?.autoPassword === '' && 'text-red-700 text-opacity-80'}`}>{newUserAccount?.username || 'Not Available'}</td>
                </tr>
              </tbody>
            </table>
         
          {/* <div className='flex flex-col gap-2 text-sm text-right font-bold'>
              <h1>Username</h1>
              <h1>Email</h1>
              <h1>Access Type</h1>
              <h1>System Password</h1>
              <h1>Custom Password</h1>
          </div>
          <div className='flex-grow flex flex-col gap-2 text-sm text-[#333] text-opacity-75'>
              <h1>{newUserAccount?.username || ''}</h1>
              <h1>{newUserAccount?.email || ''}</h1>
              <h1>Programmatic access and IAM Management console access</h1>
              <h1>No</h1>
              <h1>password123422</h1>
          </div> */}
        </div>
      </div>
        <div className=''>
        <h1 className='font-Rubik text-[#000] text-opacity-50 pt-6'>Groups Assigned</h1>
          <GroupList />
        </div>
     
    </div>
  )
}

export default UserCreationSummary
